### ISSUE TITLE
Can you implement the unicode function

### ISSUE THREAD

**Issue by zxyqq** [mvf/svn_wfx#8]
Thank you very much for this plugin. 
Browsing SVN repositorys with TC is very useful.
I use the Microsoft Visual Studio and  the lib [ https://sourceforge.net/projects/win32svn/files/1.8.17/apache24/](https://sourceforge.net/projects/win32svn/files/1.8.17/apache24)
Finally it works.
But when I browser the svn repositorys contains the chinese character, the file name list in total commander is messy code.

I search your code and found that the unicode function is missing.
Can you implement the unicode function kindly. 
Thank you !

**Comment by mvf** [comment]
Thanks for your interest and sorry for letting this sit for so long. Unfortunately I'll have to close this as a duplicate to #3. I have recently gotten back into Windows a bit, but haven't used Subversion in years. So I'm afraid I can't promise that this will be fixed any time soon.
